name: katalog
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets :
    - assets/ngegasngerem.jpg 
    - assets/sabdocinta.jpg
    - assets/lupaendonesajpg.jpg
    - assets/scaled.jpg
    - assets/merayutuhan.jpg
   - assets/sejarah.jpg
   - assets/cemburu.jpg
   - assets/crewet.jpg
    - assets/ngajionline2.jpg
  